// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPc89un-MktdCGB6LXX6XfXcs0CPecfwM',
    appId: '1:432260917968:web:8a99addd6773c7844b8cd5',
    messagingSenderId: '432260917968',
    projectId: 'flutter-test-c8dd7',
    authDomain: 'flutter-test-c8dd7.firebaseapp.com',
    storageBucket: 'flutter-test-c8dd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreqa4r8u7acTTGhQPn5dLI3BCvEcOj6w',
    appId: '1:432260917968:android:e91e869a570c05bd4b8cd5',
    messagingSenderId: '432260917968',
    projectId: 'flutter-test-c8dd7',
    storageBucket: 'flutter-test-c8dd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFZ0n868pip9d1fjjzmDIdsxd5U1by80',
    appId: '1:432260917968:ios:b567b52b77e1a33e4b8cd5',
    messagingSenderId: '432260917968',
    projectId: 'flutter-test-c8dd7',
    storageBucket: 'flutter-test-c8dd7.appspot.com',
    iosBundleId: 'com.example.ldswWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFZ0n868pip9d1fjjzmDIdsxd5U1by80',
    appId: '1:432260917968:ios:b567b52b77e1a33e4b8cd5',
    messagingSenderId: '432260917968',
    projectId: 'flutter-test-c8dd7',
    storageBucket: 'flutter-test-c8dd7.appspot.com',
    iosBundleId: 'com.example.ldswWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPc89un-MktdCGB6LXX6XfXcs0CPecfwM',
    appId: '1:432260917968:web:a0bd0c406271e42c4b8cd5',
    messagingSenderId: '432260917968',
    projectId: 'flutter-test-c8dd7',
    authDomain: 'flutter-test-c8dd7.firebaseapp.com',
    storageBucket: 'flutter-test-c8dd7.appspot.com',
  );
}
